export default [
  { name: "Abra", value: "Abra" },
  { name: "Agusan del Norte", value: "Agusan del Norte" },
  { name: "Agusan del Sur", value: "Agusan del Sur" },
  { name: "Aklan", value: "Aklan" },
  { name: "Albay", value: "Albay" },
  { name: "Antique", value: "Antique" },
  { name: "Apayao", value: "Apayao" },
  { name: "Aurora", value: "Aurora" },
  { name: "Basilan", value: "Basilan" },
  { name: "Bataan", value: "Bataan" },
  { name: "Batanes", value: "Batanes" },
  { name: "Batangas", value: "Batangas" },
  { name: "Benguet", value: "Benguet" },
  { name: "Biliran", value: "Biliran" },
  { name: "Bohol", value: "Bohol" },
  { name: "Bukidnon", value: "Bukidnon" },
  { name: "Bulacan", value: "Bulacan" },
  { name: "Cagayan", value: "Cagayan" },
  { name: "Camarines Norte", value: "Camarines Norte" },
  { name: "Camarines Sur", value: "Camarines Sur" },
  { name: "Camiguin", value: "Camiguin" },
  { name: "Capiz", value: "Capiz" },
  { name: "Catanduanes", value: "Catanduanes" },
  { name: "Cavite", value: "Cavite" },
  { name: "Cebu", value: "Cebu" },
  { name: "Compostela Valley", value: "Compostela Valley" },
  { name: "Cotabato", value: "Cotabato" },
  { name: "Davao del Norte", value: "Davao del Norte" },
  { name: "Davao del Sur", value: "Davao del Sur" },
  { name: "Davao Occidental", value: "Davao Occidental" },
  { name: "Davao Oriental", value: "Davao Oriental" },
  { name: "Dinagat Islands", value: "Dinagat Islands" },
  { name: "Eastern Samar", value: "Eastern Samar" },
  { name: "Guimaras", value: "Guimaras" },
  { name: "Ifugao", value: "Ifugao" },
  { name: "Ilocos Norte", value: "Ilocos Norte" },
  { name: "Ilocos Sur", value: "Ilocos Sur" },
  { name: "Iloilo", value: "Iloilo" },
  { name: "Isabela", value: "Isabela" },
  { name: "Kalinga", value: "Kalinga" },
  { name: "La Union", value: "La Union" },
  { name: "Laguna", value: "Laguna" },
  { name: "Lanao del Norte", value: "Lanao del Norte" },
  { name: "Lanao del Sur", value: "Lanao del Sur" },
  { name: "Leyte", value: "Leyte" },
  { name: "Maguindanao", value: "Maguindanao" },
  { name: "Marinduque", value: "Marinduque" },
  { name: "Masbate", value: "Masbate" },
  { name: "Misamis Occidental", value: "Misamis Occidental" },
  { name: "Misamis Oriental", value: "Misamis Oriental" },
  { name: "Mountain Province", value: "Mountain Province" },
  { name: "Negros Occidental", value: "Negros Occidental" },
  { name: "Negros Oriental", value: "Negros Oriental" },
  { name: "Northern Samar", value: "Northern Samar" },
  { name: "Nueva Ecija", value: "Nueva Ecija" },
  { name: "Nueva Vizcaya", value: "Nueva Vizcaya" },
  { name: "Occidental Mindoro", value: "Occidental Mindoro" },
  { name: "Oriental Mindoro", value: "Oriental Mindoro" },
  { name: "Palawan", value: "Palawan" },
  { name: "Pampanga", value: "Pampanga" },
  { name: "Pangasinan", value: "Pangasinan" },
  { name: "Quezon", value: "Quezon" },
  { name: "Quirino", value: "Quirino" },
  { name: "Rizal", value: "Rizal" },
  { name: "Romblon", value: "Romblon" },
  { name: "Samar", value: "Samar" },
  { name: "Sarangani", value: "Sarangani" },
  { name: "Siquijor", value: "Siquijor" },
  { name: "Sorsogon", value: "Sorsogon" },
  { name: "South Cotabato", value: "South Cotabato" },
  { name: "Southern Leyte", value: "Southern Leyte" },
  { name: "Sultan Kudarat", value: "Sultan Kudarat" },
  { name: "Sulu", value: "Sulu" },
  { name: "Surigao del Norte", value: "Surigao del Norte" },
  { name: "Surigao del Sur", value: "Surigao del Sur" },
  { name: "Tarlac", value: "Tarlac" },
  { name: "Tawi-Tawi", value: "Tawi-Tawi" },
  { name: "Zambales", value: "Zambales" },
  { name: "Zamboanga del Norte", value: "Zamboanga del Norte" },
  { name: "Zamboanga del Sur", value: "Zamboanga del Sur" },
  { name: "Zamboanga Sibugay", value: "Zamboanga Sibugay" },
];
